import React from 'react';
import { Award, Target, Eye, Sparkles } from 'lucide-react';

interface PromptScoreProps {
  score: {
    relevance: number;
    clarity: number;
    creativity: number;
    critique: string;
  };
}

const PromptScore: React.FC<PromptScoreProps> = ({ score }) => {
  const getScoreColor = (value: number) => {
    if (value >= 8) return 'bg-green-500';
    if (value >= 6) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const getScoreTextColor = (value: number) => {
    if (value >= 8) return 'text-green-700';
    if (value >= 6) return 'text-yellow-700';
    return 'text-red-700';
  };

  const scoreItems = [
    { 
      name: 'Relevance', 
      value: score.relevance, 
      icon: Target,
      description: 'How well the response matches the prompt'
    },
    { 
      name: 'Clarity', 
      value: score.clarity, 
      icon: Eye,
      description: 'How clear and understandable the prompt is'
    },
    { 
      name: 'Creativity', 
      value: score.creativity, 
      icon: Sparkles,
      description: 'How creative and engaging the prompt is'
    }
  ];

  const averageScore = Math.round((score.relevance + score.clarity + score.creativity) / 3 * 10) / 10;

  return (
    <div className="bg-white border border-gray-200 rounded-2xl p-8 shadow-sm">
      <div className="flex items-center space-x-3 mb-8">
        <div className="w-10 h-10 bg-black rounded-lg flex items-center justify-center">
          <Award className="w-5 h-5 text-white" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-black">PromptScore</h2>
          <p className="text-gray-600">AI-powered evaluation</p>
        </div>
      </div>

      {/* Overall Score */}
      <div className="text-center mb-8">
        <div className={`inline-flex items-center justify-center w-20 h-20 rounded-2xl ${getScoreColor(averageScore)} text-white text-3xl font-bold mb-3 shadow-sm`}>
          {averageScore}
        </div>
        <p className="text-lg font-semibold text-gray-800">Overall Score</p>
        <p className="text-sm text-gray-600">Out of 10</p>
      </div>

      {/* Individual Scores */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        {scoreItems.map((item) => {
          const Icon = item.icon;
          return (
            <div key={item.name} className="text-center">
              <div className="w-12 h-12 mx-auto mb-3 bg-gray-50 rounded-lg flex items-center justify-center border border-gray-200">
                <Icon className="w-6 h-6 text-gray-600" />
              </div>
              <div className={`text-2xl font-bold mb-1 ${getScoreTextColor(item.value)}`}>
                {item.value}
              </div>
              <div className="text-sm font-medium text-gray-800 mb-1">{item.name}</div>
              <div className="text-xs text-gray-500 leading-tight">{item.description}</div>
            </div>
          );
        })}
      </div>

      {/* Critique */}
      <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
        <h3 className="font-semibold text-black mb-3 flex items-center space-x-2">
          <Award className="w-4 h-4" />
          <span>AI Critique</span>
        </h3>
        <p className="text-gray-700 leading-relaxed">{score.critique}</p>
      </div>

      {/* Scoring Info */}
      <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200">
        <p className="text-xs text-gray-600 text-center">
          Scores are generated by GPT-4 evaluation system • Updated in real-time
        </p>
      </div>
    </div>
  );
};

export default PromptScore;